const menu = [
  {
    id: 1,
    title: "buttermilk pancakes",
    category: "desayuno",
    price: 15.99,
    img: "./images/item-1.jpeg",
    desc: `Gofres de mantequilla con salsa de sirope de arce y frutas`,
  },
  {
    id: 2,
    title: "diner double",
    category: "comida",
    price: 13.99,
    img: "./images/item-2.jpeg",
    desc: `Hamburguesa doble de ternera, sin nada que envidiar a McDonals!`,
  },
  {
    id: 3,
    title: "godzilla milkshake",
    category: "batidos",
    price: 6.99,
    img: "./images/item-3.jpeg",
    desc: `Batido tan grande como el monstruo japones, al que te costara derrotar`,
  },
  {
    id: 4,
    title: "country delight",
    category: "desayuno",
    price: 20.99,
    img: "./images/item-4.jpeg",
    desc: `Comida tipica inglesa  para despertate como si fueras la reina de inglaterra.`,
  },
  {
    id: 5,
    title: "egg attack",
    category: "comida",
    price: 22.99,
    img: "./images/item-5.jpeg",
    desc: `Hamburguesa de cerdo, y huevo frito que no te comeras sin ensuciarte, para chuparse los dedos.`,
  },
  {
    id: 6,
    title: "oreo dream",
    category: "batidos",
    price: 18.99,
    img: "./images/item-6.jpeg",
    desc: `Si eres fan de las galletas oreo, este es un batido que no te puedes perder!`,
  },
  {
    id: 7,
    title: "bacon overflow",
    category: "desayuno",
    price: 8.99,
    img: "./images/item-7.jpeg",
    desc: `Para los carnivoros de verdad, con bacon crujiente y pollo a la plancha.`,
  },
  {
    id: 8,
    title: "american classic",
    category: "comida",
    price: 12.99,
    img: "./images/item-8.jpeg",
    desc: `Sientete un verdadero americano, como si estubieras en cualquier esquina de NY.`,
  },
  {
    id: 9,
    title: "quarantine buddy",
    category: "batidos",
    price: 16.99,
    img: "./images/item-9.jpeg",
    desc: `El clasico entre los clasicos, que nunca pasa de moda y que hasta podras compartir con tu amigo de cuarentena.`,
  },
  {
    id: 10,
    title: "bison steak",
    category: "cena",
    price: 22.99,
    img: "./images/item-10.jpeg",
    desc: `Verdadera carne ahumada de bisonte, para la gente que no se llena con nada y le gusta el verdadero sabor a bisonte!`,
  },
];
